version: '3.4'
services:
  memcached:
    image: memcached
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=battles
      - POSTGRES_USER=battles
      - POSTGRES_DB=battles
  backend:
    environment:
      - WARGAMING_API
      - MEMCACHE_HOSTNAME=memcached
      - PG_NAME=battles
      - PG_USER=battles
      - PG_PASSWORD=battles
      - PG_HOST=db
    build: ./battles
    links:
      - "memcached"
      - "db"
    depends_on:
      - "memcached"
      - "db"
  frontend:
    build: ./static
    links:
      - "backend"
    ports:
      - "8000:80"
