# Generated by Django 2.0 on 2017-12-26 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_id', models.CharField(max_length=255)),
                ('arena_id', models.CharField(max_length=255)),
                ('arena_name', models.CharField(max_length=255)),
                ('province_id', models.CharField(max_length=255)),
                ('province_name', models.CharField(max_length=255)),
                ('prime_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ProvinceBattles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField()),
                ('start_at', models.DateTimeField()),
                ('clan_a', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scheduler.Clan')),
                ('clan_b', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scheduler.Clan')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(max_length=10)),
                ('arena_id', models.CharField(max_length=255, null=True)),
                ('date', models.DateField()),
                ('battles_start_at', models.DateTimeField()),
                ('is_landing', models.BooleanField(default=False)),
                ('round_number', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('STARTED', 'STARTED'), ('FINISHED', 'FINISHED')], max_length=8, null=True)),
                ('attackers', models.ManyToManyField(related_name='_schedule_attackers_+', to='scheduler.Clan')),
                ('competitors', models.ManyToManyField(related_name='_schedule_competitors_+', to='scheduler.Clan')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scheduler.Clan')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='scheduler.Province')),
            ],
        ),
        migrations.AddField(
            model_name='provincebattles',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles', to='scheduler.Schedule'),
        ),
    ]
