# Generated by Django 2.0 on 2017-12-28 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='ProvinceBattles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField()),
                ('start_at', models.DateTimeField()),
                ('clan_a', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scheduler.Clan')),
                ('clan_b', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scheduler.Clan')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_id', models.CharField(max_length=255)),
                ('front_name', models.CharField(max_length=255)),
                ('province_id', models.CharField(max_length=255)),
                ('province_name', models.CharField(max_length=255)),
                ('arena_id', models.CharField(max_length=255)),
                ('arena_name', models.CharField(max_length=255)),
                ('server', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('prime_time', models.TimeField()),
                ('battles_start_at', models.DateTimeField()),
                ('landing_type', models.CharField(choices=[(None, 'By land'), ('tournament', 'tournament')], max_length=10, null=True)),
                ('round_number', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('STARTED', 'STARTED'), ('FINISHED', 'FINISHED')], max_length=8, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scheduler.Clan')),
                ('pretenders', models.ManyToManyField(related_name='_schedule_pretenders_+', to='scheduler.Clan')),
            ],
        ),
        migrations.AddField(
            model_name='provincebattles',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles', to='scheduler.Schedule'),
        ),
    ]
